"""crear tablas Usuario y Documento

Revision ID: 24a3e06d5fcc
Revises: b9a5d33141bf
Create Date: 2026-07-15 09:18:11.670607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a3e06d5fcc'
down_revision: Union[str, Sequence[str], None] = 'b9a5d33141bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
