"""crear tablas Usuario y Documento

Revision ID: 49f85438de36
Revises: 24a3e06d5fcc
Create Date: 2026-07-15 09:37:05.759642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f85438de36'
down_revision: Union[str, Sequence[str], None] = '24a3e06d5fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NumeroDocumento', sa.String(), nullable=True),
    sa.Column('NombreCompleto', sa.String(), nullable=True),
    sa.Column('FechaNacimiento', sa.String(), nullable=True),
    sa.Column('Sexo', sa.String(), nullable=True),
    sa.Column('LugarNacimiento', sa.String(), nullable=True),
    sa.Column('Nacionalidad', sa.String(), nullable=True),
    sa.Column('TipoSangre', sa.String(), nullable=True),
    sa.Column('Programa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_documentos_Id'), 'documentos', ['Id'], unique=False)
    op.create_index(op.f('ix_documentos_NumeroDocumento'), 'documentos', ['NumeroDocumento'], unique=True)
    op.create_table('usuarios',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.Column('Apellido', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Password', sa.String(), nullable=True),
    sa.Column('ConteoIngresos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_usuarios_Email'), 'usuarios', ['Email'], unique=True)
    op.create_index(op.f('ix_usuarios_Id'), 'usuarios', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_Id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_Email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_documentos_NumeroDocumento'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_Id'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
